### ISSUE TITLE
Unable to read pdf / Failed to open "...pdf" for reading

### ISSUE THREAD

**Issue by harrisontaee** [alpha0010/react-native-pdf-viewer#12]
Cannot seem to get pdf to render.
Picking a document from the local filing system and loading the uri into the source gives the error "Unable to read pdf '...pdf".
Using PdfUtil.getPageCount() gives the message: "Failed to open '...pdf' for reading".

Not sure what to do and need this package to work for my application. Any suggestions would be greatly appreciated!

*Note: file uri sent to source looks like:
```file:///var/mobile/Containers/Data/Application/951BA543-63C8-465F-A0D0-1D0AAA5DE099/Library/Caches/DocumentPicker/43F3C96E-8BC6-46EF-B852-8C7128417E62.pdf```

**Comment by alpha0010** [comment]
This library assumes paths of form `/var/mobile/Containers/Data/Application/951BA543-63C8-465F-A0D0-1D0AAA5DE099/Library/Caches/DocumentPicker/43F3C96E-8BC6-46EF-B852-8C7128417E62.pdf` (no leading `file://`).

However, `file://` seems to be popular with other libraries, so I suppose I should add support for it here.

**Comment by hpwtaee** [comment]
Thanks so much for the speedy reply @alpha0010
I just removed the file prefix and it works now. Glad it’s a simple fix but recommend support for it in the future!
