### ISSUE TITLE
Annotation rendering?

### ISSUE THREAD

**Issue by ahrampy** [alpha0010/react-native-pdf-viewer#14]
Is there some extra step needed when passing annotations to the Pdf component? Just passing in a test annotation array as `annotation={JSON.stringify(example)}` where `example` is the array given here: https://github.com/alpha0010/paged-annotation#example doesn't seem to show up.

Using `"react-native-pdf-light": "^2.0.2"`

Thank you for building this!!

**Comment by alpha0010** [comment]
Annotations are read from the filesystem, so you will need to save the JSON to a file.  Pass the path to the file to the Pdf component `annotation={'/path/to/data.json'}`.

The example project shows a way of [loading from bundled asset](https://github.com/alpha0010/react-native-pdf-viewer/blob/v2.0.2/example/src/App.tsx#L8-L11).

Code snippet from my app.  You can of course change to your preferred filesystem library.

```tsx
import { Dirs, FileSystem } from 'react-native-file-access';

// [...] Generate `output` in some way.

const path = `${Dirs.DocumentDir}/example.annotation`;

// Limit precision of coordinates. Yields smaller files.
const rounded = JSON.stringify(output, (_key, value) => {
  if (typeof value === 'number') {
    return parseFloat(value.toFixed(5));
  }
  return value;
});

try {
  await FileSystem.writeFile(path, rounded);
} catch (e) {
  // Handle the error.
}

// [...]

<Pdf source={source} annotation={path} />
```
