### ISSUE TITLE
How to open password protected pdf?

### ISSUE THREAD

**Issue by sonywijaya** [alpha0010/react-native-pdf-viewer#18]
When I open password protected pdf it gives the error `[Error: password required or incorrect password]`
Is it possible to insert the password?

**Comment by alpha0010** [comment]
The system library `android.graphics.pdf.PdfRenderer`, which this uses for rendering, unfortunately does not support encrypted PDFs.

If you need to use password protected PDFs, try `react-native-pdf` (which bundles its own renderer, instead of depending on the system library).
