### ISSUE TITLE
can you give a example on how to show a local pdf file ?

### ISSUE THREAD

**Issue by KingAmo** [alpha0010/react-native-pdf-viewer#2]
i try a lot , still can not display a pdf file any way

**Comment by alpha0010** [comment]
The `source` prop requires the full path to a pdf located in the filesystem.  If the pdf is bundled with app assets (for example, [android](https://github.com/alpha0010/react-native-pdf-viewer/tree/v1.3.2/example/android/app/src/main/assets)), you can use the [`PdfUtil` helper](https://github.com/alpha0010/react-native-pdf-viewer/blob/v1.3.2/example/src/App.tsx#L7) to extract it.

If it is sourced from elsewhere, you will have to retrieve the path from that library.  For example, with `rn-fetch-blob`,
```tsx
const source = `${RNFetchBlob.fs.dirs.DocumentDir}/example.pdf`;
const response = await RNFetchBlob.config({
  path: source,
}).fetch('GET', 'https://example.com/example.pdf');

// ...

<Pdf source={source} />
```
