### ISSUE TITLE
Pinch to zoom on FlatList collection

### ISSUE THREAD

**Issue by iliascandis** [alpha0010/react-native-pdf-viewer#23]
So there is no way to have pinch to zoom enabled across the Pdf flatlist ?

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by alpha0010** [comment]
Nothing prebuilt for that currently (pull requests welcome, of course).  You can try the suggestions in https://github.com/alpha0010/react-native-pdf-viewer/issues/13 .

An architecture decision I made with this library is to control most actions JS-side, and have native-side only handle rendering individual pages.  This has the advantage of allowing much more control and customization in app.  However, it also means all native interaction features must be implemented JS-side.

If you do not utilize the extra control this library provides, the newer `react-native-pdf-renderer` or the more established `react-native-pdf` might better fit your needs.
