### ISSUE TITLE
Black bars on IOS with <PdfView> component

### ISSUE THREAD

**Issue by sean-yeoh** [alpha0010/react-native-pdf-viewer#3]
Hi @alpha0010, thanks for the library.

I'm currently getting weird black bars when using `<PdfView>` component on IOS. It works fine on Android. Is there a way to fix this?
![image](https://user-images.githubusercontent.com/18374402/108521511-c2323380-7306-11eb-8ccb-a84179f4f605.png)

React Native version: 0.63

**Comment by alpha0010** [comment]
Could you provide a pdf file the results in this behavior?

**Comment by sean-yeoh** [comment]
Hi @alpha0010 , I fixed it by adding a view with style `{ backgroundColor: 'transparent', borderColor: 'white', borderWidth: 8, position: 'absolute' }` with width and height of the pdfview and it seems to work ok. It's just a list of pdf thumbnails so i think its fine.

Thanks!
