### ISSUE TITLE
uri is not dipalying

### ISSUE THREAD

**Issue by swaroopaillinda** [alpha0010/react-native-pdf-viewer#5]
Hi,

I am using u r module I need to display pdf with specific page number 
but the pdf is a Uri format

How Can I display that
Here is my code:

`  <PdfView  resizeMode={"contain"}
         source={"..."}
         page={parseInt(item)} 
         onError={(error)=>console.log("ffff",error)}/>`

the errror is cannot open the pdf file

Can u help me with this

**Comment by alpha0010** [comment]
Could you explain what you mean by "Uri format"?  Do you have an example I can see?

**Comment by swaroopaillinda** [comment]
@alpha0010 ----
 https://smarttesting.s3.ap-south-1.amazonaws.com/image/icon-customresources/Time_and_Work_PDF-1617259083278.pdf

getting this error
 {"message": "File 'https://smarttesting.s3.ap-south-1.amazonaws.com/image/icon-customresources/Time_and_Work_PDF-1617259083278.pdf' not found."}

**Comment by alpha0010** [comment]
This library does not include networking code, so you will have to use a different library to download the pdf first.  `react-native-file-access` is a library I created that can be used like:

```tsx
import {Dirs, FileSystem} from 'react-native-file-access';

const cachePath = Dirs.CacheDir + '/name.pdf';
await FileSystem.fetch('https://example.com/name.pdf', {path: cachePath});

// ...

<PdfView resizeMode={"contain"} source={cachePath} page={parseInt(item)} onError={(error) => console.log("ffff", error)} />
```

However, any library that can download files should work.  Other examples:
- `expo-file-system`
- `rn-fetch-blob`
- `react-native-fs`
- `react-native-blob-courier`

**Comment by alpha0010** [comment]
Assuming resolved.
