### ISSUE TITLE
Clickable links Feature request

### ISSUE THREAD

**Issue by evanjmg** [alpha0010/react-native-pdf-viewer#6]
I know this is a simplified library, but I'm sure it's possible to add clickable links on pdfs right for both android and ios. Seems like a basic feature requirement - to navigate to different parts of pdf

**Comment by alpha0010** [comment]
Unfortunately https://developer.android.com/reference/android/graphics/pdf/PdfRenderer on Android does not expose this information in its API.

**Comment by evanjmg** [comment]
Ah ok so pdfium is an open source solution that supports it. I will use react native pdf then as it supports this but sucks that android doesn’t natively support it.
