### ISSUE TITLE
Zoom in/out not possible?

### ISSUE THREAD

**Issue by ilyagru** [alpha0010/react-native-pdf-viewer#9]
Since it's just a FlatList with page cells, zooming in and out with pinch gestures will not be possible with this library?

**Comment by alpha0010** [comment]
This library does not have interaction support.  You could build your own https://github.com/alpha0010/react-native-pdf-viewer/issues/7#issuecomment-839908031 .

I have tried a couple options for implementing in the FlatList (not just single pages), but none of them worked very well.

(Of course, pull requests welcome.)
